services:
  web:
    container_name: website_here
    image: flaskplanet/gitdeploy
    ports:
      - "5000" # The port the flask app is running on
      - "9898" # The port that GitDeploy is running on
    volumes:
      - instance:/gitdeploy/instance
      - repo:/gitdeploy/repo

volumes:
  instance:
  repo:

# adding the repo dir will allow you to rebuild the container but keep the repo safe,
# this is a good idea if you have user data in a local sqlite database
