[flask]
APP_NAME = "autogit"
VERSION = "0.0.1"
SECRET_KEY = "<AUTOGIT_SK>"
DEBUG = false
TESTING = false
SESSION_TIME = 480
ERROR_404_HELP = false
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXPLAIN_TEMPLATE_LOADING = false
